# 🐼 Pandas Function Practice

This notebook is a structured walkthrough of commonly used `pandas` functions and operations.  
It is **not tied to any specific dataset**, and is designed to help explore syntax and behavior through minimal examples.

> ✅ No plotting, data loading, or visualization — just core pandas functionality.

In [1]:
import pandas as pd
import numpy as np

# 🧱 1. Creating Data
✅ Creating a DataFrame from a simple dictionary

✅ Adding/removing Rows

✅ Adding/removing Rows

In [2]:
# Creating a DataFrame from a Python dictionary with two columns: `A` and `B`.
data = {
    'A': [1,2,3,4,5,6,7,8,9,10],
    'B': [10,20,30,40,50,60,70,80,90,100]
}
df = pd.DataFrame(data)
print(df)

    A    B
0   1   10
1   2   20
2   3   30
3   4   40
4   5   50
5   6   60
6   7   70
7   8   80
8   9   90
9  10  100

### ➕ Adding Columns

In [3]:
# Add one column
df['C'] = [3,5,12,3,6,1,5,15,23,9]

# Add multiple columns
df = df.assign(
    D = np.random.randint(10, 30, 10),
    E = np.random.randint(40, 60, 10)
)
print(df)

    A    B   C   D   E
0   1   10   3  24  42
1   2   20   5  26  49
2   3   30  12  20  47
3   4   40   3  23  54
4   5   50   6  18  55
5   6   60   1  15  41
6   7   70   5  12  46
7   8   80  15  26  51
8   9   90  23  18  41
9  10  100   9  16  56

### ➕ Adding Rows

In [ ]:
# Add individual rows using `.loc[]`. Be sure to provide values for all columns.

# Get the number of rows and columns of the dataset
rows, columns = df.shape
print(f'row = {rows} , columns = {columns}')

df.loc[10] = [11, 110, 7, 22, 45] 
df.loc[15] = [15, 150, 15, 43, 34]
df

row = 10 , columns = 5

     A    B   C   D   E
0    1   10   3  24  42
1    2   20   5  26  49
2    3   30  12  20  47
3    4   40   3  23  54
4    5   50   6  18  55
5    6   60   1  15  41
6    7   70   5  12  46
7    8   80  15  26  51
8    9   90  23  18  41
9   10  100   9  16  56
10  11  110   7  22  45
15  15  150  15  43  34

In [ ]:
# Add multiple rows using `concat()`
# This method we don't have to assign the number of row that we want to add.
# It will append the new rows to the end.

new_rows = pd.DataFrame([
    {'A': 12, 'B': 120, 'C': 8, 'D': 24, 'E': 46},
    {'A': 13, 'B': 130, 'C': 9, 'D': 26, 'E': 47}
])
df = pd.concat([df, new_rows], ignore_index=True)
print(df)

     A    B   C   D   E
0    1   10   3  24  42
1    2   20   5  26  49
2    3   30  12  20  47
3    4   40   3  23  54
4    5   50   6  18  55
5    6   60   1  15  41
6    7   70   5  12  46
7    8   80  15  26  51
8    9   90  23  18  41
9   10  100   9  16  56
10  11  110   7  22  45
11  15  150  15  43  34
12  12  120   8  24  46
13  13  130   9  26  47

### ➖ Removing Columns
We can drop columns using their names or by index position by using `drop()` function. Always set `axis=1` to indicate you're working with columns.

axis = 0 is to remove `rows` >> this is defaults value

In [9]:
# Drop a single column by using its name
print('Columns : ', df.columns)
print(df.drop(['A'], axis=1))

Columns :  Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
      B   C   D   E
0    10   3  24  42
1    20   5  26  49
2    30  12  20  47
3    40   3  23  54
4    50   6  18  55
5    60   1  15  41
6    70   5  12  46
7    80  15  26  51
8    90  23  18  41
9   100   9  16  56
10  110   7  22  45
11  150  15  43  34
12  120   8  24  46
13  130   9  26  47

In [7]:
# Drop multiple columns
print(df.drop(['A', 'C'], axis=1))

      B   D   E
0    10  24  42
1    20  26  49
2    30  20  47
3    40  23  54
4    50  18  55
5    60  15  41
6    70  12  46
7    80  26  51
8    90  18  41
9   100  16  56
10  110  22  45
11  150  43  34
12  120  24  46
13  130  26  47

In [12]:
# Drop columns using column index positions
print('Columns : ', df.columns)
print(df.drop(df.columns[[1,3,4]], axis = 1))

Columns :  Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
     A   C
0    1   3
1    2   5
2    3  12
3    4   3
4    5   6
5    6   1
6    7   5
7    8  15
8    9  23
9   10   9
10  11   7
11  15  15
12  12   8
13  13   9

In [ ]:
# Drop a range of columns using index slicing
print(df.drop(df.iloc[:, 1:3], axis=1))

     A   D   E
0    1  24  42
1    2  26  49
2    3  20  47
3    4  23  54
4    5  18  55
5    6  15  41
6    7  12  46
7    8  26  51
8    9  18  41
9   10  16  56
10  11  22  45
11  15  43  34
12  12  24  46
13  13  26  47

### 🗑️ Removing Rows by index:

In [13]:
# Drop a single row
print(df.drop([6]))

     A    B   C   D   E
0    1   10   3  24  42
1    2   20   5  26  49
2    3   30  12  20  47
3    4   40   3  23  54
4    5   50   6  18  55
5    6   60   1  15  41
7    8   80  15  26  51
8    9   90  23  18  41
9   10  100   9  16  56
10  11  110   7  22  45
11  15  150  15  43  34
12  12  120   8  24  46
13  13  130   9  26  47

In [14]:
# Drop multiple rows
print(df.drop([1,3,5,6]))

     A    B   C   D   E
0    1   10   3  24  42
2    3   30  12  20  47
4    5   50   6  18  55
7    8   80  15  26  51
8    9   90  23  18  41
9   10  100   9  16  56
10  11  110   7  22  45
11  15  150  15  43  34
12  12  120   8  24  46
13  13  130   9  26  47

In [15]:
# Drop a range of rows using index slicing
print(df.drop(df.iloc[3:7,:].index))

     A    B   C   D   E
0    1   10   3  24  42
1    2   20   5  26  49
2    3   30  12  20  47
7    8   80  15  26  51
8    9   90  23  18  41
9   10  100   9  16  56
10  11  110   7  22  45
11  15  150  15  43  34
12  12  120   8  24  46
13  13  130   9  26  47

# 🔍 2. Indexing and Selection
`.loc[]` , `.iloc[]`

`.loc[]` based on Labels (index or column name) >> `df.loc[row_label, col_label]`

`.iloc[]` based on Integer positions >> `df.iloc[row_index, col_index]`

Including: 
- Selecting individual items
- Selecting multiple rows/columns
- Slicing data ranges
- Using custom row indexes

In [65]:
# Create the DataFrame
data = {
  'Name': ['Ankit', 'Amit', 'Aishwarya', 'Priyanka', 'Priya', 'Shaurya', 'Nataya'],
  'Age': [21, 23, 20, 18, 17, 23, 19],
  'Stream': ['Math', 'Commerce', 'Science', 'Math', 'Math', 'Science', 'Commerce'],
  'Percentage': [88, 92, 95, 70, 65, 78, 80]
}
df_grade = pd.DataFrame(data)
df_grade

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   23  Commerce          92
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
4      Priya   17      Math          65
5    Shaurya   23   Science          78
6     Nataya   19  Commerce          80

### 🎯 Select a Single Value
- `.loc[row_label, column_label]`
- `.iloc[row_index, column_index]`

In [66]:
print('Use loc to get item : ', df_grade.loc[2,'Name'])
print('Use iloc to get item : ', df_grade.iloc[2, 0])

Use loc to get item :  Aishwarya
Use iloc to get item :  Aishwarya

### 🎯 Select Multiple Rows and Columns

In [67]:
# Pass lists of rows and columns.
print(df_grade.loc[ [0,2],['Name', 'Age'] ])
print('\n')
print(df_grade.iloc[ [0,2],[0, 1] ])

        Name  Age
0      Ankit   21
2  Aishwarya   20


        Name  Age
0      Ankit   21
2  Aishwarya   20

In [68]:
# Select a Range of Rows and Columns
print(df_grade.loc[1:4, 'Age':'Stream'])
print('\n')
print(df_grade.iloc[1:-2, :])

   Age    Stream
1   23  Commerce
2   20   Science
3   18      Math
4   17      Math


        Name  Age    Stream  Percentage
1       Amit   23  Commerce          92
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
4      Priya   17      Math          65

### 🧾 Change Row Index Labels
After setting custom row labels, we can still use `.loc[]`.

In [84]:
df_grade.index = ['ID0', 'ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'ID6']
print(df_grade)
print('\n')
print(df_grade.loc['ID1':'ID4', 'Age':'Stream'])

          Name  Age    Stream  Percentage
ID0      Ankit   21      Math          88
ID1       Amit   23  Commerce          92
ID2  Aishwarya   20   Science          95
ID3   Priyanka   18      Math          70
ID4      Priya   17      Math          65
ID5    Shaurya   23   Science          78
ID6     Nataya   19  Commerce          80


     Age    Stream
ID1   23  Commerce
ID2   20   Science
ID3   18      Math
ID4   17      Math

### ✅ Select Entire Row or Column

In [70]:
print(df_grade.loc['ID2'])      # Entire row
print('\n')
print(df_grade['Stream'])       # Entire column

Name          Aishwarya
Age                  20
Stream          Science
Percentage           95
Name: ID2, dtype: object


ID0        Math
ID1    Commerce
ID2     Science
ID3        Math
ID4        Math
ID5     Science
ID6    Commerce
Name: Stream, dtype: object

# 📏 3. Condition-Based Selection
Filtering of rows using conditions on column values.  

Include:
- Filter by single or multiple conditions
- Use `.isin()` to check for multiple matches
- Use `~` to invert conditions
- Filter by string content

### ✅ `df[condition]` : Filter rows by a boolean condition

In [ ]:
df_grade = pd.DataFrame(data)

# Filter rows where Age > 20
df_grade[df_grade['Age'] > 20]

      Name  Age    Stream  Percentage
0    Ankit   21      Math          88
1     Amit   23  Commerce          92
5  Shaurya   23   Science          78

Rows and Columns Selection in one go by `df[column][df[condition]]`

In [78]:
print(df_grade['Name'][df_grade['Age'] > 20])
print('\nTo list ::: ')
print(df_grade['Name'][df_grade['Age'] > 20].tolist())

ID0      Ankit
ID1       Amit
ID5    Shaurya
Name: Name, dtype: object

To list :::
['Ankit', 'Amit', 'Shaurya']

### ✅ Combine Multiple Conditions (AND)

In [72]:
df_grade[(df_grade['Age'] > 20) & (df_grade['Stream'] == 'Commerce')]

     Name  Age    Stream  Percentage
ID1  Amit   23  Commerce          92

In [86]:
# Use `.query()` for readable filtering
df_grade.query("Age > 20 and Stream == 'Commerce'")

   Name  Age    Stream  Percentage
1  Amit   23  Commerce          92

Use `.loc[]` with condition

In [73]:
df_grade.loc[df_grade['Age'] > 20]

        Name  Age    Stream  Percentage
ID0    Ankit   21      Math          88
ID1     Amit   23  Commerce          92
ID5  Shaurya   23   Science          78

### ✅ Use `.isin()` to match multiple values

In [ ]:
options = ['Math', 'Commerce']
print('Result in isin() ::')
print(df_grade[df_grade['Stream'].isin(options)])

# Use `~` to invert a condition (NOT in list)
print('\nResult not in isin() :: ')
print(df_grade[~df_grade['Stream'].isin(options)])

Result in isin() ::
         Name  Age    Stream  Percentage
ID0     Ankit   21      Math          88
ID1      Amit   23  Commerce          92
ID3  Priyanka   18      Math          70
ID4     Priya   17      Math          65
ID6    Nataya   19  Commerce          80

Result not in isin() ::
          Name  Age   Stream  Percentage
ID2  Aishwarya   20  Science          95
ID5    Shaurya   23  Science          78

Use `.str.contains()` to filter by text in a string column

In [ ]:
print(df[df['Name'].str.contains('Pri')])

       Name  Age Stream  Percentage
3  Priyanka   18   Math          70
4     Priya   17   Math          65

Use `.between()` for range filtering

In [88]:
df_grade[df_grade['Age'].between(18, 21)]

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
6     Nataya   19  Commerce          80

# 🏆 4. Sorting and Ranking

Sort and Rank data in a DataFrame by using:
- `.sort_values()` — Sort by one or more column values
- `.sort_index()` — Sort by the row index
- `.rank()` — Assign ranks to numeric values

In [122]:
df_grade = pd.DataFrame(data)

df_grade.loc[3, "Percentage"] = 78 # Duplicate percentage to test tied ranks
df_grade.loc[4, "Percentage"] = 78 # Duplicate percentage to test tied ranks
df_grade.loc[6, "Percentage"] = 78 # Duplicate percentage to test tied ranks

### 🏅 Add Ranking Based on Percentage
The `.rank()` function assigns a rank to each value.  
Ties result in averaged ranks by default.

Since the Ranking 1-4 has the same Percentage value >> All of them have the same Ranking :: (1+2+3+4)/4 = 2.5

In [ ]:
df_grade['Ranking'] = df_grade['Percentage'].rank(ascending=1)
df_grade

        Name  Age    Stream  Percentage  Ranking
0      Ankit   21      Math          88      5.0
1       Amit   23  Commerce          92      6.0
2  Aishwarya   20   Science          95      7.0
3   Priyanka   18      Math          78      2.5
4      Priya   17      Math          78      2.5
5    Shaurya   23   Science          78      2.5
6     Nataya   19  Commerce          78      2.5

`rank(method='dense')` 
- The `dense` method assigns the same rank to ties, but keeps the next rank sequential.

In [124]:
df_grade['Rank_Dense'] = df_grade['Percentage'].rank(method='dense')
df_grade

        Name  Age    Stream  Percentage  Ranking  Rank_Dense
0      Ankit   21      Math          88      5.0         2.0
1       Amit   23  Commerce          92      6.0         3.0
2  Aishwarya   20   Science          95      7.0         4.0
3   Priyanka   18      Math          78      2.5         1.0
4      Priya   17      Math          78      2.5         1.0
5    Shaurya   23   Science          78      2.5         1.0
6     Nataya   19  Commerce          78      2.5         1.0

### 🔢 Setting a different column as index can help in sorting or indexing.

inplace: Boolean; if True, modifies the original DataFrame

`df_grade = df_grade.set_index('Ranking')` == `df_grade.set_index('Ranking', inplace=True)`

In [148]:
df_grade = pd.DataFrame(data)
df_grade.loc[3, "Percentage"] = 78 # Duplicate percentage to test tied ranks
df_grade['Ranking'] = df_grade['Percentage'].rank(ascending=1)

df_grade.set_index('Ranking', inplace=True)
print(df_grade)

              Name  Age    Stream  Percentage
Ranking
5.0          Ankit   21      Math          88
6.0           Amit   23  Commerce          92
7.0      Aishwarya   20   Science          95
2.5       Priyanka   18      Math          78
1.0          Priya   17      Math          65
2.5        Shaurya   23   Science          78
4.0         Nataya   19  Commerce          80

Sort by Index (Row Labels)

In [149]:
df_grade.sort_index()

              Name  Age    Stream  Percentage
Ranking
1.0          Priya   17      Math          65
2.5       Priyanka   18      Math          78
2.5        Shaurya   23   Science          78
4.0         Nataya   19  Commerce          80
5.0          Ankit   21      Math          88
6.0           Amit   23  Commerce          92
7.0      Aishwarya   20   Science          95

### 🔃 Sort by Column

In [150]:
df_grade.sort_values(by='Age', ascending= False)

              Name  Age    Stream  Percentage
Ranking
6.0           Amit   23  Commerce          92
2.5        Shaurya   23   Science          78
5.0          Ankit   21      Math          88
7.0      Aishwarya   20   Science          95
4.0         Nataya   19  Commerce          80
2.5       Priyanka   18      Math          78
1.0          Priya   17      Math          65

Sort by Multiple Columns
- Sort by `Age` descending, and break ties with `Ranking` ascending.

In [151]:
df_grade.sort_values(by=['Age', 'Ranking'], ascending= [False, True], inplace=True)
print(df_grade)

              Name  Age    Stream  Percentage
Ranking
2.5        Shaurya   23   Science          78
6.0           Amit   23  Commerce          92
5.0          Ankit   21      Math          88
7.0      Aishwarya   20   Science          95
4.0         Nataya   19  Commerce          80
2.5       Priyanka   18      Math          78
1.0          Priya   17      Math          65

- Use `na_position='first'` or `'last'` to control where `NaNs` appear

By default, `sort_values()` places `NaN` values at the end of the sorted result.  
You can control this behavior using the `na_position` parameter.

- `na_position='first'` puts missing values at the top
- `na_position='last'` (default) puts them at the bottom

In [152]:
df_grade.iloc[3,1] = np.nan
df_grade

              Name   Age    Stream  Percentage
Ranking
2.5        Shaurya  23.0   Science          78
6.0           Amit  23.0  Commerce          92
5.0          Ankit  21.0      Math          88
7.0      Aishwarya   NaN   Science          95
4.0         Nataya  19.0  Commerce          80
2.5       Priyanka  18.0      Math          78
1.0          Priya  17.0      Math          65

In [155]:
print("Sort by Percentage (NaNs last - default):")
print(df_grade.sort_values(by='Age'))

print("\nSort by Percentage (NaNs first):")
print(df_grade.sort_values(by='Age', na_position='first'))

Sort by Percentage (NaNs last - default):
              Name   Age    Stream  Percentage
Ranking
1.0          Priya  17.0      Math          65
2.5       Priyanka  18.0      Math          78
4.0         Nataya  19.0  Commerce          80
5.0          Ankit  21.0      Math          88
2.5        Shaurya  23.0   Science          78
6.0           Amit  23.0  Commerce          92
7.0      Aishwarya   NaN   Science          95

Sort by Percentage (NaNs first):
              Name   Age    Stream  Percentage
Ranking
7.0      Aishwarya   NaN   Science          95
1.0          Priya  17.0      Math          65
2.5       Priyanka  18.0      Math          78
4.0         Nataya  19.0  Commerce          80
5.0          Ankit  21.0      Math          88
2.5        Shaurya  23.0   Science          78
6.0           Amit  23.0  Commerce          92

# 🧪 5. Conditional Column Creation & Mapping

This section covers how to:
- Use `.map()` with custom functions or dictionaries
- Use `np.where()` to conditionally assign values
- Use `.loc[]` for condition-based updates
- Fill missing values with `.fillna()`

In [167]:
df_grade = pd.DataFrame(data)
df_grade

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   23  Commerce          92
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
4      Priya   17      Math          65
5    Shaurya   23   Science          78
6     Nataya   19  Commerce          80

### Use a Custom Function with `.map()` to Categorize Grades

In [170]:
def grade_stats(value):
    if value < 50:
        return "very low"
    if 50 <= value < 65:
        return "low"
    elif 65 <= value < 75:
        return "average"
    elif 75 <= value < 90:
        return "better"
    elif value >= 90:
        return "very good"

df_grade['grade_stats'] = df_grade['Percentage'].map(grade_stats)
df_grade

        Name  Age    Stream  Percentage grade_stats
0      Ankit   21      Math          88      better
1       Amit   23  Commerce          92   very good
2  Aishwarya   20   Science          95   very good
3   Priyanka   18      Math          70     average
4      Priya   17      Math          65     average
5    Shaurya   23   Science          78      better
6     Nataya   19  Commerce          80      better

### Map Strings to New Values Using a Dictionary

In [172]:
mappings = {
    'Math': 'Building_1',
    'Science': 'Building_2'
}

df_grade['Building'] = df_grade['Stream'].map(mappings)
df_grade

        Name  Age    Stream  Percentage grade_stats    Building
0      Ankit   21      Math          88      better  Building_1
1       Amit   23  Commerce          92   very good         NaN
2  Aishwarya   20   Science          95   very good  Building_2
3   Priyanka   18      Math          70     average  Building_1
4      Priya   17      Math          65     average  Building_1
5    Shaurya   23   Science          78      better  Building_2
6     Nataya   19  Commerce          80      better         NaN

- Handle Missing Values with `.fillna()`
- Replace NaNs (from unmapped categories) with `'Others'`.

In [173]:
df_grade = df_grade.fillna('Others')
df_grade

        Name  Age    Stream  Percentage grade_stats    Building
0      Ankit   21      Math          88      better  Building_1
1       Amit   23  Commerce          92   very good      Others
2  Aishwarya   20   Science          95   very good  Building_2
3   Priyanka   18      Math          70     average  Building_1
4      Priya   17      Math          65     average  Building_1
5    Shaurya   23   Science          78      better  Building_2
6     Nataya   19  Commerce          80      better      Others

### Use `np.where()` for Inline Binary Classification
Create a new column based on a condition

In [174]:
df_grade['Age>20'] = np.where(df_grade['Age'] >= 20, 'Yes', 'No')
df_grade

        Name  Age    Stream  Percentage grade_stats    Building Age>20
0      Ankit   21      Math          88      better  Building_1    Yes
1       Amit   23  Commerce          92   very good      Others    Yes
2  Aishwarya   20   Science          95   very good  Building_2    Yes
3   Priyanka   18      Math          70     average  Building_1     No
4      Priya   17      Math          65     average  Building_1     No
5    Shaurya   23   Science          78      better  Building_2    Yes
6     Nataya   19  Commerce          80      better      Others     No

### Update Values Conditionally Using `.loc[]`
Change the building label for Science stream students.

In [176]:
df_grade.loc[df_grade['Stream'] == 'Science', 'Building'] = 'Building_3'
df_grade

        Name  Age    Stream  Percentage grade_stats    Building Age>20
0      Ankit   21      Math          88      better  Building_1    Yes
1       Amit   23  Commerce          92   very good      Others    Yes
2  Aishwarya   20   Science          95   very good  Building_3    Yes
3   Priyanka   18      Math          70     average  Building_1     No
4      Priya   17      Math          65     average  Building_1     No
5    Shaurya   23   Science          78      better  Building_3    Yes
6     Nataya   19  Commerce          80      better      Others     No

# 🧮 6. Aggregation and Descriptive Statistics

This section explores how to calculate summary statistics using:
- `.sum()`, `.mean()`, `.median()`, `.describe()`
- `.agg()` for applying multiple functions at once
- `.groupby()` for grouped statistics
- `.value_counts()` for categorical frequencies

In [177]:
df_stat = pd.DataFrame(data)

### Basic Summary Functions
✅ .max(), .min(), .mean(), .sum(), .median()
These functions compute column-wise summary statistics for numerical data.
- `.max()` – Maximum value
- `.min()` – Minimum value
- `.mean()` – Average (mean)
- `.sum()` – Total sum
- `.median()` – Middle value

In [ ]:
# Find Max in every field
print(df_stat.max())

Name          Shaurya
Age                23
Stream        Science
Percentage         95
dtype: object

In [ ]:
# Find max in 1 specific field
print('max_age : ', max(df_stat['Age']))
print('min_age : ', df_stat.Age.min())

max_age :  23
min_age :  17

In [ ]:
# Get the Row(s) with the Max Value
print(df_stat[df_stat.Age == df_stat.Age.max()])

      Name  Age    Stream  Percentage
1     Amit   23  Commerce          92
5  Shaurya   23   Science          78

In [231]:
# Alternative ways to apply the statistic function
print('Max Percentage across every value: ', df_stat['Percentage'].max())
print('Min Percentage in range [0:3]: ' ,df.iloc[0:3]['Percentage'].min())
print('\nMax Percentage and Age: \n', df_stat[['Percentage', 'Age']].max())
print('\nGet only Max percentage value:', df_stat[['Percentage', 'Age']].max().iloc[0])

Max Percentage across every value:  95
Min Percentage in range [0:3]:  88

Max Percentage and Age:
 Percentage    95
Age           23
dtype: int64

Get only Max percentage value: 95

In [ ]:
# Mean of Selected Columns
print('Mean Age and Percentage: \n', df_stat[['Age', 'Percentage']].mean())

Mean Age and Percentage:
 Age           20.142857
Percentage    81.142857
dtype: float64

### Full Summary with `.describe()`
Returns a quick summary of numeric columns: count, mean, std, min, max, and quartiles (25%, 50%, 75%).
Very useful for initial data inspection.

In [191]:
print(df_stat.describe())

             Age  Percentage
count   7.000000    7.000000
mean   20.142857   81.142857
std     2.340126   11.201616
min    17.000000   65.000000
25%    18.500000   74.000000
50%    20.000000   80.000000
75%    22.000000   90.000000
max    23.000000   95.000000

### Aggregating with `.agg()`
Use .agg() to apply multiple functions to one or more columns.
It’s more flexible than writing .mean(), .min(), etc., separately. Moreover, can custom the function.

In [192]:
df_stat.agg(
    {
        'Age' : ['min', 'max', 'median'],
        'Percentage' : ['min', 'max', 'median']
    }
)

         Age  Percentage
min     17.0        65.0
max     23.0        95.0
median  20.0        80.0

### Aggregating statistics grouped by category

Groups your data by one or more categorical columns, and applies summary stats.

Use when you want to know:
- Average score by stream
- Count per category
- Stats per subgroup (e.g., year & stream)

This function fits in the more general split-apply-combine pattern:
- Split the data into groups
- Apply a function to each group independently
- Combine the results into a data structure

The apply and combine steps are typically done together in pandas.

In [195]:
df_stat[['Stream', 'Percentage']].groupby('Stream').mean()

          Percentage
Stream
Commerce   86.000000
Math       74.333333
Science    86.500000

In [200]:
df_stat.groupby('Stream')['Percentage'].mean()

Stream
Commerce    86.000000
Math        74.333333
Science     86.500000
Name: Percentage, dtype: float64

🔍 1. `df_stat[['Stream', 'Percentage']].groupby('Stream').mean()`

✅ What it does:
- First `selects only the Stream and Percentage columns.`
- Then groups by Stream.
- Finally, computes the mean for only the numeric columns (in this case just Percentage).

🧠 Why Use This:
- Useful if you want to restrict aggregation only to selected columns before grouping.

📦 Output:
- A `DataFrame` with Stream as the index and Percentage as the column.


🔍 2. `df_stat.groupby('Stream')['Percentage'].mean()`

✅ What it does:
- First `groups the entire DataFrame by Stream.`
- Then selects the Percentage column after grouping.
- Then computes the mean.

🧠 Why Use This:
- More explicit when you're working with a single column.
- Cleaner if you're not planning to include any other column in the aggregation.

📦 Output:
A `Series` — not a DataFrame — where:
- Index is `Stream`
- Values are the mean of `Percentage`

In [233]:
print('Output as DataFrame : ', df_stat.groupby(['Stream','Year'])['Percentage'].mean().iloc[0])
print('Output as Series : ', df_stat[['Stream','Year', 'Percentage']].groupby(['Stream','Year']).mean().iloc[0]['Percentage'])

Output as DataFrame :  86.0
Output as Series :  86.0

In [ ]:
# Find the mean to all column that is numberic only
df_stat.groupby('Stream').mean(numeric_only=True)

                Age  Percentage
Stream
Commerce  21.000000   86.000000
Math      18.666667   74.333333
Science   21.500000   86.500000

### Group by Multiple Columns (e.g. Stream and Year)

In [206]:
df_stat['Year'] = [1,3,2,2,1,2,3]
df_stat

        Name  Age    Stream  Percentage  Year
0      Ankit   21      Math          88     1
1       Amit   23  Commerce          92     3
2  Aishwarya   20   Science          95     2
3   Priyanka   18      Math          70     2
4      Priya   17      Math          65     1
5    Shaurya   23   Science          78     2
6     Nataya   19  Commerce          80     3

In [210]:
df_stat.groupby(['Stream','Year'])['Percentage'].mean()

Stream    Year
Commerce  3       86.0
Math      1       76.5
          2       70.0
Science   2       86.5
Name: Percentage, dtype: float64

In [208]:
df_stat[['Stream','Year', 'Percentage']].groupby(['Stream','Year']).mean()

               Percentage
Stream   Year
Commerce 3           86.0
Math     1           76.5
         2           70.0
Science  2           86.5

### `.value_counts()`
Returns the frequency of unique values in a column — great for checking category distributions.

In [ ]:
# How many students are in each stream?
df_stat['Stream'].value_counts()

Stream
Math        3
Commerce    2
Science     2
Name: count, dtype: int64

### 🔗 7. Joining and Merging

This section explores how to combine multiple DataFrames using:
- `pd.concat()` for stacking
- `pd.merge()` for SQL-style joins
- `.join()` for index-based merging

These functions help when you need to merge datasets from different sources or shapes.

### `pd.concat()` — Combine Along Rows or Columns

Similar to append from list
- Append in vertical (add more role) >> axis = 0 : default
- Append in horizontal (add more column) >> axis = 1

In [ ]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [4, 5],
    'Name': ['David', 'Eve']
})

# Stack rows (vertical concatenation)
df_concat_rows = pd.concat([df1, df2], ignore_index=True)
print("Concatenate Rows:\n", df_concat_rows)

Concatenate Rows:
    ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eve

In [ ]:
# Stack columns (horizontal concatenation) by using axis=1
df3 = pd.DataFrame({
    'Score': [90, 85, 88]
})

df_concat_cols = pd.concat([df1, df3], axis=1)
print("Concatenate Columns:\n", df_concat_cols)

Concatenate Columns:
    ID     Name  Score
0   1    Alice     90
1   2      Bob     85
2   3  Charlie     88


| Feature                   | `.join()`                                          | `pd.merge()`                                |
| ------------------------- | -------------------------------------------------- | ------------------------------------------- |
| **Primary use**           | Index-based joins                                  | SQL-style joins on column(s)                |
| **Default key**           | Joins on the **index** of the calling DataFrame    | Joins on a **common column** (`on='col'`)   |
| **Ease of use**           | Simpler when indexes are already aligned           | More flexible and explicit                  |
| **Join types**            | Supports `'left'`, `'right'`, `'outer'`, `'inner'` | Same (`how=` parameter)                     |
| **Syntax style**          | Method: `df1.join(df2)`                            | Function: `pd.merge(df1, df2, on='col')`    |
| **Multiple keys**         | ❌ Not directly supported                         | ✅ Yes (`on=['key1', 'key2']`)              |
| **Column name conflicts** | Needs handling with `lsuffix`, `rsuffix`           | Can handle duplicate columns more elegantly |

### `pd.merge()` — SQL-style Joins
- Combine on column keys (SQL)
- Based on Column Values

In [236]:
students = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Class': ['A', 'B', 'A', 'C']
})

scores = pd.DataFrame({
    'ID': [1, 2, 4, 5],
    'Score': [90, 85, 88, 70]
})

In [ ]:
# Inner Merge (default)
print("Inner Merge:\n", pd.merge(students, scores, on='ID'))

Inner Join:
    ID   Name Class  Score
0   1  Alice     A     90
1   2    Bob     B     85
2   4  David     C     88

In [ ]:
# Left Merge
print("Left Merge:\n", pd.merge(students, scores, on='ID', how='left'))

Left Join:
    ID     Name Class  Score
0   1    Alice     A   90.0
1   2      Bob     B   85.0
2   3  Charlie     A    NaN
3   4    David     C   88.0

In [ ]:
# Right Merge
print("Right Merge:\n", pd.merge(students, scores, on='ID', how='right'))

Right Join:
    ID   Name Class  Score
0   1  Alice     A     90
1   2    Bob     B     85
2   4  David     C     88
3   5    NaN   NaN     70

In [ ]:
# Outer Merge
print("Outer Merge:\n", pd.merge(students, scores, on='ID', how='outer'))

Outer Join:
    ID     Name Class  Score
0   1    Alice     A   90.0
1   2      Bob     B   85.0
2   3  Charlie     A    NaN
3   4    David     C   88.0
4   5      NaN   NaN   70.0

In [ ]:
students = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6],
    'Name': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Class': ['Math', 'Sci', 'Art', 'Sci', 'Math', 'Sci']
})

sci_scores = pd.DataFrame({
    'ID': [1, 2, 4, 5, 7, 8],
    'Score': [90, 85, 88, 70, 60, 52],
    'Class': ['Sci', 'Sci', 'Sci', 'Sci', 'Sci', 'Sci']
})

# Merge with Multiple keys
print("Inner Merge:\n", pd.merge(students, sci_scores, on=['ID', 'Class']))

Inner Merge:
    ID Name Class  Score
0   2    B   Sci     85
1   4    D   Sci     88

### `.join()` — Simpler Index-Based Join
- Combine on index
- Based on Index

In [249]:
grades = pd.DataFrame({
    'Grade': ['A', 'B', 'C', 'D'],
}, index=['ID1', 'ID2', 'ID3', 'ID4'])

comments = pd.DataFrame({
    'Comment': ['Excellent', 'Good', 'Average', 'Bad']
}, index=['ID1', 'ID2', 'ID4', 'ID5'])

# Join on index (how >> Default 'left')
print("Join on index:\n",  grades.join(comments))

Join on index:
     Grade    Comment
ID1     A  Excellent
ID2     B       Good
ID3     C        NaN
ID4     D    Average

In [250]:
# Right Join
print("Right Join:\n", grades.join(comments, how='right'))

Right Join:
     Grade    Comment
ID1     A  Excellent
ID2     B       Good
ID4     D    Average
ID5   NaN        Bad

In [251]:
# Inner Join
print("Inner Join:\n", grades.join(comments, how='inner'))

Inner Join:
     Grade    Comment
ID1     A  Excellent
ID2     B       Good
ID4     D    Average

In [248]:
df1 = pd.DataFrame(
    {
      'ID': [1, 2, 3], 
      'Name': ['Alice', 'Bob', 'Charlie']
    }
)
df2 = pd.DataFrame(
    {
      'Score': [90, 80, 70]
    }
)

# Two dataframe cannot have the share keys name
df1.join(df2)  # Joins on index

   ID     Name  Score
0   1    Alice     90
1   2      Bob     80
2   3  Charlie     70

### 🔁 8. Iteration and Row-wise Operations
.iterrows(), .itertuples()

### `.items()` – Iterate Over Columns
Iterates over each column, returning the column name and the entire column as a Series.

In [260]:
data = {
  "firstname": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]
}

df = pd.DataFrame(data)

for key, value in df.items():
  print('First item (key) : \n',key)
  print('\nSecond item (value) : \n',value)
  print('--------------------------')

First item (key) :
 firstname

Second item (value) :
 0    Sally
1     Mary
2     John
Name: firstname, dtype: object
--------------------------
First item (key) :
 age

Second item (value) :
 0    50
1    40
2    30
Name: age, dtype: int64
--------------------------

### `.iterrows()`

The iterrows() method generates an iterator object of the DataFrame, allowing us to iterate each row in the DataFrame.

Each iteration produces an index object and a row object (a Pandas Series object).

>> Iterate Over Rows (Slow, but Common)
>> - Returns each row as an (index, Series) pair.
>> - Use when you need access to row data by column name.

✅ Use .iterrows() when:
- You need access to column names
- You're building a new list or conditionally modifying data

In [254]:
data = {'Item': ['Apple', 'Reduce_A', 'Reduce_B', 'Reduce_c','Banana', 'Orange'],
        'Quantity': [10, 4, 1, 2, 20, 30],
        'Price': [5, -2, -10, -5, 3, 7,]}
df = pd.DataFrame(data)
total_sales = []
# Iterating over rows
for index, row in df.iterrows():
    if row['Price'] > 0:
        total_sales.append(row['Quantity'] * row['Price'])
    else:
        total_sales.append(0)

df['total_sales'] = total_sales
print(df)

       Item  Quantity  Price  total_sales
0     Apple        10      5           50
1  Reduce_A         4     -2            0
2  Reduce_B         1    -10            0
3  Reduce_c         2     -5            0
4    Banana        20      3           60
5    Orange        30      7          210

### `.itertuples()`

The itertuples() method generates an iterator object of the DataFrame, ***returning each row as a Pyton Tuple object***.

>> Faster Row Iteration
>> - Returns each row as a namedtuple — access is done by position (faster than .iterrows()).

✅ Use .itertuples() when:
- You don’t need to modify the DataFrame
- Speed is more important than column name access

In [ ]:
data = {
  "firstname": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]
}

df = pd.DataFrame(data)

for row in df.itertuples():
  print(row)
  print('Age : ', row[2])

Pandas(Index=0, firstname='Sally', age=50)
Age :  50
Pandas(Index=1, firstname='Mary', age=40)
Age :  40
Pandas(Index=2, firstname='John', age=30)
Age :  30

: