# 🐼 Pandas Function Exploration

This notebook is a simple walkthrough the commonly used `pandas` functions and operations.
This is designed to help explore syntax and behavior through minimal examples.

> ✅ No plotting, data loading, or visualization - just core pandas fuctionality

Ref: https://www.geeksforgeeks.org/pandas-practice-excercises-questions-and-solutions/

In [255]:
import pandas as pd
import numpy as np

(Done)🧱 2. Creating Data
Creating Series and DataFrames

From dicts, lists, NumPy, etc.

Adding/removing columns

(Done)🔍 3. Indexing and Selection
.loc[], .iloc[], .at[], .iat[]

Boolean indexing

Slicing rows/columns

(Done)🧹 4. Cleaning and Modifying Data
.drop(), .fillna(), .replace()

.astype() type conversion

Renaming columns

Removing duplicates

(Done)🧮 5. Aggregation and Statistics
.sum(), .mean(), .describe(), etc.

.value_counts()

.groupby(), .agg()

🔄 6. Reshaping and Pivoting
.melt(), .pivot()

.stack(), .unstack()

🔗 7. Joining and Merging
pd.concat(), pd.merge(), .join()

(No)📅 8. Working with Dates
pd.to_datetime()

.dt.year, .dt.month, etc.

Filtering by date

🧵 9. Working with Strings
.str.lower(), .str.contains()

.str.extract(), .str.replace()

(Done)🧰 10. Function Application
.apply(), .map(), .applymap()

Lambda functions

(Done)🧽 11. Sorting and Ranking
.sort_values(), .sort_index()

.rank()

🔁 12. Iteration and Row-wise Operations
.iterrows(), .itertuples()

Row-wise computations

In [256]:
# Done
data = {
    'A': np.random.randint(1, 20, 10),  # Random integers from 1 to 20
    'B': np.random.randint(10, 30, 10),
    'Method': np.random.choice(['Multiple', 'Sum'], 10)  # Random categorical values
}
df = pd.DataFrame(data)
print(df)

    A   B    Method
0   8  18       Sum
1   2  19       Sum
2   6  10  Multiple
3   3  22       Sum
4   4  13       Sum
5  16  11  Multiple
6  11  16  Multiple
7   4  24  Multiple
8   2  19       Sum
9  15  19       Sum

In [257]:
# Add another column: Vectorized operations
df['Result'] = np.where(df['Method'] == 'Multiple', df['A'] * df['B'], df['A'] + df['B'])
print(df)

    A   B    Method  Result
0   8  18       Sum      26
1   2  19       Sum      21
2   6  10  Multiple      60
3   3  22       Sum      25
4   4  13       Sum      17
5  16  11  Multiple     176
6  11  16  Multiple     176
7   4  24  Multiple      96
8   2  19       Sum      21
9  15  19       Sum      34

In [258]:
data = {'Item': ['Apple', 'Banana', 'Orange'],'Quantity': [10, 20, 30],'Price': [5, 3, 7]}
df = pd.DataFrame(data)
df['Sales'] = df['Quantity'] * df['Price']
print(df)

     Item  Quantity  Price  Sales
0   Apple        10      5     50
1  Banana        20      3     60
2  Orange        30      7    210

In [259]:
# Adding or multiple in list
print([1,2,3,4,5] + [10,20,30,40,50])
print([2] * 10)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [260]:
data = {'Item': ['Apple', 'Reduce_A', 'Reduce_B', 'Reduce_c','Banana', 'Orange'],
        'Quantity': [10, 4, 1, 2, 20, 30],
        'Price': [5, -2, -10, -5, 3, 7,]}
df = pd.DataFrame(data)
total_sales = []
# Iterating over rows
for index, row in df.iterrows():
    if row['Price'] > 0:
        total_sales.append(row['Quantity'] * row['Price'])
    else:
        total_sales.append(0)

df['total_sales'] = total_sales
print(df)

       Item  Quantity  Price  total_sales
0     Apple        10      5           50
1  Reduce_A         4     -2            0
2  Reduce_B         1    -10            0
3  Reduce_c         2     -5            0
4    Banana        20      3           60
5    Orange        30      7          210

In [261]:
df['Compare_total_sales'] = np.where(df['Price'] > 0, df['Quantity'] * df['Price'], 0)
print(df)

       Item  Quantity  Price  total_sales  Compare_total_sales
0     Apple        10      5           50                   50
1  Reduce_A         4     -2            0                    0
2  Reduce_B         1    -10            0                    0
3  Reduce_c         2     -5            0                    0
4    Banana        20      3           60                   60
5    Orange        30      7          210                  210

Selecting rows in pandas DataFrame based on conditions

In [262]:
data = {
  'Name': ['Ankit', 'Amit', 'Aishwarya', 'Priyanka', 'Priya', 'Shaurya' ],
  'Age': [21, 19, 20, 18, 17, 21],
  'Stream': ['Math', 'Commerce', 'Science', 'Math', 'Math', 'Science'],
  'Percentage': [88, 92, 95, 70, 65, 78]
}
df = pd.DataFrame(data)

# selecting rows based on condition
grade_a = df[df['Percentage'] >= 80]
print(grade_a)

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95

In [263]:
pos_price = df['Name'][df['Percentage'] >= 80]
print(pos_price)
print('\n')
print(pos_price.tolist())

0        Ankit
1         Amit
2    Aishwarya
Name: Name, dtype: object


['Ankit', 'Amit', 'Aishwarya']

In [264]:
# isin() like 'in' list
options = ['Math', 'Commerce']

# selecting rows based on condition in options
rslt_df = df[df['Stream'].isin(options)]
print('Result dataframe :\n', rslt_df)

# selecting rows based on condition outside options
rslt_df = df[~df['Stream'].isin(options)]

print('\nResult dataframe :\n', rslt_df)

Result dataframe :
        Name  Age    Stream  Percentage
0     Ankit   21      Math          88
1      Amit   19  Commerce          92
3  Priyanka   18      Math          70
4     Priya   17      Math          65

Result dataframe :
         Name  Age   Stream  Percentage
2  Aishwarya   20  Science          95
5    Shaurya   21  Science          78

In [265]:
# Selecting rows based on multiple column conditions using '&' operator.
rslt_df = df[(df['Age'] == 21) & (df['Stream'].isin(options))]
print(rslt_df)

    Name  Age Stream  Percentage
0  Ankit   21   Math          88

In [266]:
print(df[df['Name'].str.contains('Pri')])

       Name  Age Stream  Percentage
3  Priyanka   18   Math          70
4     Priya   17   Math          65

In [267]:
# Similiar to list when ex_list[i]
print(df)
# Iterate over rows using .iloc[] (index-based)
print("\nUsing iloc[] for index-based iteration:")
print(df.iloc[1])

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
4      Priya   17      Math          65
5    Shaurya   21   Science          78

Using iloc[] for index-based iteration:
Name              Amit
Age                 19
Stream        Commerce
Percentage          92
Name: 1, dtype: object

In [268]:
df.index = ['ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'ID6']

print(df)
# Iterate over rows using .loc[] (label-based)
print("\nUsing loc[] for label-based iteration:")
print(df.loc['ID3'])

          Name  Age    Stream  Percentage
ID1      Ankit   21      Math          88
ID2       Amit   19  Commerce          92
ID3  Aishwarya   20   Science          95
ID4   Priyanka   18      Math          70
ID5      Priya   17      Math          65
ID6    Shaurya   21   Science          78

Using loc[] for label-based iteration:
Name          Aishwarya
Age                  20
Stream          Science
Percentage           95
Name: ID3, dtype: object

In [269]:
print('Use loc to get item : ', df.loc['ID3','Name'])
print('Use iloc to get item : ', df.iloc[2, 0])

print('.values ', df.loc['ID3'].values)
print('Use loc with .values to get item : ', df.loc['ID3'].values[0])

Use loc to get item :  Aishwarya
Use iloc to get item :  Aishwarya
.values  ['Aishwarya' np.int64(20) 'Science' np.int64(95)]
Use loc with .values to get item :  Aishwarya

In [270]:
# Get multiple columns and row
print(df.loc[ ['ID1','ID3'],['Name', 'Age'] ])

          Name  Age
ID1      Ankit   21
ID3  Aishwarya   20

In [271]:
print(df.iloc[ 1:3, 2:4 ])

       Stream  Percentage
ID2  Commerce          92
ID3   Science          95

In [272]:
print(df)
print('\n')
# Delect by using the row or columns that we want to remain
print(df.iloc[1:-2, :])
print('\n')
print(df.iloc[:, :2])

          Name  Age    Stream  Percentage
ID1      Ankit   21      Math          88
ID2       Amit   19  Commerce          92
ID3  Aishwarya   20   Science          95
ID4   Priyanka   18      Math          70
ID5      Priya   17      Math          65
ID6    Shaurya   21   Science          78


          Name  Age    Stream  Percentage
ID2       Amit   19  Commerce          92
ID3  Aishwarya   20   Science          95
ID4   Priyanka   18      Math          70


          Name  Age
ID1      Ankit   21
ID2       Amit   19
ID3  Aishwarya   20
ID4   Priyanka   18
ID5      Priya   17
ID6    Shaurya   21

In [273]:
# Delect by using the row or columns that we want to delete
print(df.drop(['ID1', 'ID4']))
print('\n')
print(df.drop(df.iloc[:, 1:2], axis=1))

          Name  Age    Stream  Percentage
ID2       Amit   19  Commerce          92
ID3  Aishwarya   20   Science          95
ID5      Priya   17      Math          65
ID6    Shaurya   21   Science          78


          Name    Stream  Percentage
ID1      Ankit      Math          88
ID2       Amit  Commerce          92
ID3  Aishwarya   Science          95
ID4   Priyanka      Math          70
ID5      Priya      Math          65
ID6    Shaurya   Science          78

In [274]:
df[(df['Age'] >= 18) & (df['Age'] <=20)]

          Name  Age    Stream  Percentage
ID2       Amit   19  Commerce          92
ID3  Aishwarya   20   Science          95
ID4   Priyanka   18      Math          70

In [275]:
indexAge = df[(df['Age'] >= 18) & (df['Age'] <=20)].index
df.drop(indexAge)

        Name  Age   Stream  Percentage
ID1    Ankit   21     Math          88
ID5    Priya   17     Math          65
ID6  Shaurya   21  Science          78

# Insert row

In [276]:
# Let's create the dataframe
print(df)
print('\n')
rows, columns = df.shape

# Function to insert row in the dataframe
def Insert_row_(row_number, df, row_value):
    # Slice the upper half of the dataframe
    df1 = df.iloc[0:row_number]
 
    # Store the result of lower half of the dataframe
    df2 = df.iloc[row_number:]
 
    # Insert the row in the upper half dataframe
    df1.loc[row_number]=row_value
 
    # Concat the two dataframes
    df_result = pd.concat([df1, df2])
 
    # Reassign the index labels
    df_result.index = [*range(df_result.shape[0])]
 
    # Return the updated dataframe
    return df_result
 
# Let's create a row which we want to insert
row_number = 2
row_value = ['Add_1', 25, 'Science', 85]

if row_number > rows:
    print("Invalid row_number")
else:

    # Let's call the function and insert the row
    # at the second position
    df = Insert_row_(row_number, df, row_value)

    # Print the updated dataframe
    print(df)

          Name  Age    Stream  Percentage
ID1      Ankit   21      Math          88
ID2       Amit   19  Commerce          92
ID3  Aishwarya   20   Science          95
ID4   Priyanka   18      Math          70
ID5      Priya   17      Math          65
ID6    Shaurya   21   Science          78


        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2      Add_1   25   Science          85
3  Aishwarya   20   Science          95
4   Priyanka   18      Math          70
5      Priya   17      Math          65
6    Shaurya   21   Science          78

C:\Users\pkuso\AppData\Local\Temp\ipykernel_125112\3179345794.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[row_number]=row_value

# Ranking and sort_index

In [277]:
data = {
  'Name': ['Ankit', 'Amit', 'Aishwarya', 'Priyanka', 'Priya', 'Shaurya' ],
  'Age': [21, 19, 20, 18, 17, 21],
  'Stream': ['Math', 'Commerce', 'Science', 'Math', 'Math', 'Science'],
  'Percentage': [88, 92, 95, 70, 65, 70]
}
df = pd.DataFrame(data)
print(df)
df['Ranking'] = df['Percentage'].rank(ascending=1)
df

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
3   Priyanka   18      Math          70
4      Priya   17      Math          65
5    Shaurya   21   Science          70

        Name  Age    Stream  Percentage  Ranking
0      Ankit   21      Math          88      4.0
1       Amit   19  Commerce          92      5.0
2  Aishwarya   20   Science          95      6.0
3   Priyanka   18      Math          70      2.5
4      Priya   17      Math          65      1.0
5    Shaurya   21   Science          70      2.5

In [278]:
df = df.set_index('Ranking')
df

              Name  Age    Stream  Percentage
Ranking
4.0          Ankit   21      Math          88
5.0           Amit   19  Commerce          92
6.0      Aishwarya   20   Science          95
2.5       Priyanka   18      Math          70
1.0          Priya   17      Math          65
2.5        Shaurya   21   Science          70

In [279]:
df.sort_index()

              Name  Age    Stream  Percentage
Ranking
1.0          Priya   17      Math          65
2.5       Priyanka   18      Math          70
2.5        Shaurya   21   Science          70
4.0          Ankit   21      Math          88
5.0           Amit   19  Commerce          92
6.0      Aishwarya   20   Science          95

# Sort value

In [280]:
df.sort_values(by='Age', ascending= False)

              Name  Age    Stream  Percentage
Ranking
4.0          Ankit   21      Math          88
2.5        Shaurya   21   Science          70
6.0      Aishwarya   20   Science          95
5.0           Amit   19  Commerce          92
2.5       Priyanka   18      Math          70
1.0          Priya   17      Math          65

# Max and Min

In [281]:
df.max() # Max in every field

Name          Shaurya
Age                21
Stream        Science
Percentage         95
dtype: object

In [282]:
print(max(df['Age']))
print(type(max(df['Age'])))

21
<class 'int'>

In [283]:
print(df.Age.min())
print(df[df.Age == df.Age.min()])

17
          Name  Age Stream  Percentage
Ranking
1.0      Priya   17   Math          65

# Get Columns

In [284]:
print('df.columns         : ', df.columns)
print('list(df.columns)   : ', list(df.columns))
print('df.columns.values  : ', df.columns.values)

df.columns         :  Index(['Name', 'Age', 'Stream', 'Percentage'], dtype='object')
list(df.columns)   :  ['Name', 'Age', 'Stream', 'Percentage']
df.columns.values  :  ['Name' 'Age' 'Stream' 'Percentage']

In [285]:
df = df.set_axis(['Name_col', 'Age_col', 'Stream_col', 'Percentage_col'], axis = 1)
df

          Name_col  Age_col Stream_col  Percentage_col
Ranking
4.0          Ankit       21       Math              88
5.0           Amit       19   Commerce              92
6.0      Aishwarya       20    Science              95
2.5       Priyanka       18       Math              70
1.0          Priya       17       Math              65
2.5        Shaurya       21    Science              70

# Mapping

In [286]:
def grade_stats(value):
    if value < 50:
        return "very low"
    if 50 <= value < 65:
        return "low"
    elif 65 <= value < 75:
        return "average"
    elif 75 <= value < 90:
        return "better"
    elif value >= 90:
        return "very good"

df['grade_stats'] = df['Percentage_col'].map(grade_stats)
df

          Name_col  Age_col Stream_col  Percentage_col grade_stats
Ranking
4.0          Ankit       21       Math              88      better
5.0           Amit       19   Commerce              92   very good
6.0      Aishwarya       20    Science              95   very good
2.5       Priyanka       18       Math              70     average
1.0          Priya       17       Math              65     average
2.5        Shaurya       21    Science              70     average

In [287]:
mappings = {
    'Math': 'Building_1',
    'Science': 'Building_2'
}

df['Building'] = df['Stream_col'].map(mappings)
df

          Name_col  Age_col Stream_col  Percentage_col grade_stats    Building
Ranking
4.0          Ankit       21       Math              88      better  Building_1
5.0           Amit       19   Commerce              92   very good         NaN
6.0      Aishwarya       20    Science              95   very good  Building_2
2.5       Priyanka       18       Math              70     average  Building_1
1.0          Priya       17       Math              65     average  Building_1
2.5        Shaurya       21    Science              70     average  Building_2

In [288]:
df = df.iloc[:, :-1]
df['Building_col'] = 'Others'
df.loc[df['Stream_col'] == 'Math', 'Building_col'] = 'Building_1'
df.loc[df['Stream_col'] == 'Science', 'Building_col'] = 'Building_2'
df

,Name_col,Age_col,Stream_col,Percentage_col,grade_stats,Building_col
Ranking,,,,,,
4.0,Ankit,21,Math,88,better,Building_1
5.0,Amit,19,Commerce,92,very good,Others
6.0,Aishwarya,20,Science,95,very good,Building_2
2.5,Priyanka,18,Math,70,average,Building_1
1.0,Priya,17,Math,65,average,Building_1
2.5,Shaurya,21,Science,70,average,Building_2

In [289]:
df['Name_col'] = ['Ankit AAA', 'Amit BBB', 'Aishwarya CCC', 'Priyanka DDD', 'Priya EEE', 'Shaurya FFF']
df

,Name_col,Age_col,Stream_col,Percentage_col,grade_stats,Building_col
Ranking,,,,,,
4.0,Ankit AAA,21,Math,88,better,Building_1
5.0,Amit BBB,19,Commerce,92,very good,Others
6.0,Aishwarya CCC,20,Science,95,very good,Building_2
2.5,Priyanka DDD,18,Math,70,average,Building_1
1.0,Priya EEE,17,Math,65,average,Building_1
2.5,Shaurya FFF,21,Science,70,average,Building_2

In [290]:
df[['First_Name', 'Last_Name']] = df['Name_col'].str.split(expand=True)
df

,Name_col,Age_col,Stream_col,Percentage_col,grade_stats,Building_col,First_Name,Last_Name
Ranking,,,,,,,,
4.0,Ankit AAA,21,Math,88,better,Building_1,Ankit,AAA
5.0,Amit BBB,19,Commerce,92,very good,Others,Amit,BBB
6.0,Aishwarya CCC,20,Science,95,very good,Building_2,Aishwarya,CCC
2.5,Priyanka DDD,18,Math,70,average,Building_1,Priyanka,DDD
1.0,Priya EEE,17,Math,65,average,Building_1,Priya,EEE
2.5,Shaurya FFF,21,Science,70,average,Building_2,Shaurya,FFF

In [291]:
df = df.drop(['grade_stats', 'Building_col', 'First_Name', 'Last_Name'], axis=1)
df

              Name_col  Age_col Stream_col  Percentage_col
Ranking
4.0          Ankit AAA       21       Math              88
5.0           Amit BBB       19   Commerce              92
6.0      Aishwarya CCC       20    Science              95
2.5       Priyanka DDD       18       Math              70
1.0          Priya EEE       17       Math              65
2.5        Shaurya FFF       21    Science              70

In [292]:
df['Name_col'] = ['Ankit', 'Amit', 'Aishwarya', 'Priyanka', 'Priya', 'Shaurya']
df

          Name_col  Age_col Stream_col  Percentage_col
Ranking
4.0          Ankit       21       Math              88
5.0           Amit       19   Commerce              92
6.0      Aishwarya       20    Science              95
2.5       Priyanka       18       Math              70
1.0          Priya       17       Math              65
2.5        Shaurya       21    Science              70

In [293]:
data = {
  'Name': ['Ankit', 'Amit', 'Aishwarya', 'Priyanka', 'Priya', 'Shaurya' ],
  'Age': [21, 19, 20, 18, 17, 21],
  'Stream': ['Math', 'Commerce', 'Science', 'Math', 'Math', 'Science'],
  'Percentage': [88, 92, 95, 70, 65, 70]
}
df = pd.DataFrame(data)
row_number = 3
row_value = ['Zemba', 21, 'Science', 90]
df = Insert_row_(row_number, df, row_value)
df

C:\Users\pkuso\AppData\Local\Temp\ipykernel_125112\3179345794.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[row_number]=row_value

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
3      Zemba   21   Science          90
4   Priyanka   18      Math          70
5      Priya   17      Math          65
6    Shaurya   21   Science          70

# Min, Max, Ordering

In [294]:
print('Percentage all max : ', df['Percentage'].max())
print('Percentage [0:3] min : ' ,df.iloc[0:3]['Percentage'].min())

Percentage all max :  95
Percentage [0:3] min :  88

In [295]:
print(df.nlargest(3,['Age', 'Percentage']))

      Name  Age   Stream  Percentage
3    Zemba   21  Science          90
0    Ankit   21     Math          88
6  Shaurya   21  Science          70

In [296]:
row_number = 3
row_value = ['Zemba_2', 21, 'Science', 90]
df = Insert_row_(row_number, df, row_value)
df

C:\Users\pkuso\AppData\Local\Temp\ipykernel_125112\3179345794.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[row_number]=row_value

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
3    Zemba_2   21   Science          90
4      Zemba   21   Science          90
5   Priyanka   18      Math          70
6      Priya   17      Math          65
7    Shaurya   21   Science          70

In [297]:
df.drop(df[df['Name'] == 'Zemba_2'].index)

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
4      Zemba   21   Science          90
5   Priyanka   18      Math          70
6      Priya   17      Math          65
7    Shaurya   21   Science          70

In [298]:
df.drop(6)

        Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20   Science          95
3    Zemba_2   21   Science          90
4      Zemba   21   Science          90
5   Priyanka   18      Math          70
7    Shaurya   21   Science          70

In [299]:
df.drop(['Age'], axis=1)

        Name    Stream  Percentage
0      Ankit      Math          88
1       Amit  Commerce          92
2  Aishwarya   Science          95
3    Zemba_2   Science          90
4      Zemba   Science          90
5   Priyanka      Math          70
6      Priya      Math          65
7    Shaurya   Science          70

In [300]:
# Drop columns based on index positions
df.drop(df.columns[[0, 1]], axis=1)

     Stream  Percentage
0      Math          88
1  Commerce          92
2   Science          95
3   Science          90
4   Science          90
5      Math          70
6      Math          65
7   Science          70

In [301]:
df.drop(df.iloc[:, 0:2], axis=1)

     Stream  Percentage
0      Math          88
1  Commerce          92
2   Science          95
3   Science          90
4   Science          90
5      Math          70
6      Math          65
7   Science          70

# Capitalize first letter

In [302]:
# creating a dataframe 
df = pd.DataFrame({'A': ['john', 'bODAY', 'minA', 'Peter', 'nicky'], 
				'B': ['masters', 'graduate', 'graduate', 
								'Masters', 'Graduate'], 
				'C': [27, 23, 21, 23, 24]}) 

df['A'] = df['A'].str.capitalize() 
df

       A         B   C
0   John   masters  27
1  Boday  graduate  23
2   Mina  graduate  21
3  Peter   Masters  23
4  Nicky  Graduate  24

# Data cleaning

In [303]:
# create a dictionary with five fields each
data = {
    'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
    'B': ['B1', 'B2', 'B3', 'B4', 'B4'],
    'C': ['C1', 'C2', 'C3', 'C3', 'C3'],
    'D': ['D1', 'D2', 'D2', 'D2', 'D2'],
    'E': ['E1', 'E1', 'E1', 'E1', 'E1']}

df = pd.DataFrame(data)
df

    A   B   C   D   E
0  A1  B1  C1  D1  E1
1  A2  B2  C2  D2  E1
2  A3  B3  C3  D2  E1
3  A4  B4  C3  D2  E1
4  A5  B4  C3  D2  E1

In [304]:
print('unique() : ',df['B'].unique())
print('value_count() : \n', df['D'].value_counts())

unique() :  ['B1' 'B2' 'B3' 'B4']
value_count() :
 D
D2    4
D1    1
Name: count, dtype: int64

In [305]:
unique_c = df['C'].drop_duplicates()
unique_c

0    C1
1    C2
2    C3
Name: C, dtype: object